name: collapse-env

channels:
  - conda-forge
  - defaults

dependencies:
  - coverage
  - matplotlib
  - numpy
  - pip
  - pip:
      - palettable
  - pytest
  - pytest-mock
  - python=3.8
  - scipy
  - sympy
