name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-matrix:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.7", "3.8" ]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: collapse-env
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#      - name: Add Conda
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda init bash
          conda activate collapse-env
      #      - name: Lint with flake8
      #        run: |
      #          conda install flake8
      #          # stop the build if there are Python syntax errors or undefined names
      #          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Test Suite
        run: |
          pytest
